### ISSUE TITLE
Please add some examples about how to load a string to the template

### ISSUE THREAD

**Issue by akshay-since1987** [salsify/broccoli-underscore-template-compiler#1]

**Comment by dfreeman** [comment]
The templates produced are just the output of Underscore's `_.template` function, so you can use them as [their documentation](http://underscorejs.org/#template) suggests:

```js
var compiled = _.template("hello: <%= name %>");
compiled({name: 'moe'});
//=> "hello: moe"

var template = _.template("<b><%- value %></b>");
template({value: '<script>'});
//=> "<b>&lt;script&gt;</b>"
```

Does that answer your question? If so, I'll add that link and snippet to the README.

**Comment by akshay-since1987** [comment]
Yeah I think That does answer my question. Thanks.

**Comment by dfreeman** [comment]
Updated the README. Thanks for the report!
